version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - master-api
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-net

  ai-api:
    build: ./ai_api
    ports:
      - "5000:5000"
    networks:
      - app-net

  master-api:
    build: ./master-api
    ports:
      - "9000:9000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
