version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - ai-api
      - master-api

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  ai-api:
    build: ./ai_api
    ports:
      - "5000:5000"
    volumes:
      - ./ai_api:/app

  master-api:
    build: ./master-api
    ports:
      - "9000:9000"
    volumes:
      - ./master-api:/app
